name: Test and Publish

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
        arch: ["x64"]
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          architecture: ${{ matrix.arch }}
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip pytest

      - name: Install pyfmodex
        run: |
          pip install .

      - name: Run tests
        run: |
          $arch = '${{ matrix.arch }}'
          if ($IsWindows) {
            $env:PYFMODEX_DLL_PATH = '${{ github.workspace }}/tests/lib/Windows/fmod.dll'
            $env:PYFMODEX_STUDIO_DLL_PATH = '${{ github.workspace }}/tests/lib/Windows/fmodstudio.dll'
          }
          elseif ($IsMacOS) {
            $env:PYFMODEX_DLL_PATH = '${{ github.workspace }}/tests/lib/Darwin/libfmod.dylib'
            $env:PYFMODEX_STUDIO_DLL_PATH = '${{ github.workspace }}/tests/lib/Darwin/libfmodstudio.dylib'
          }
          else {
            $env:PYFMODEX_DLL_PATH = '${{ github.workspace }}/tests/lib/Linux/libfmod.so'
            $env:PYFMODEX_STUDIO_DLL_PATH = '${{ github.workspace }}/tests/lib/Linux/libfmodstudio.so'
          }
          pytest -vs
        shell: pwsh
